### ISSUE TITLE
[PE-D] Number of digits in phone number 

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-W14-3/tp#103]
Group should specify target audience and restrict the number of digits in the phone number based on the target country. 

![image.png](https://raw.githubusercontent.com/soloplxya/ped/main/files/3604b498-4841-4b5f-9ad9-82d4cd074e36.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: soloplxya/ped#1

**Comment by albertsutz** [comment]
TBD
