### ISSUE TITLE
[PE-D] Wrong time format in documentation

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-W14-3/tp#115]
Instead of using HH:MM, HH:mm should be used to reflect time format instead. 

![image.png](https://raw.githubusercontent.com/soloplxya/ped/main/files/31729aac-453c-4744-b1c4-53962abae965.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: soloplxya/ped#4

**Comment by Graphcalibur** [comment]
Reason for not an issue: They're the same thing
