### ISSUE TITLE
[PE-D] Overlapping events can occur

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-W14-3/tp#117]
Not sure if this is intended behaviour. Can add overlapping events. Similarly, can also edit them so they overlap. 

![image.png](https://raw.githubusercontent.com/tanyjnaaman/ped/main/files/10270592-48fb-407e-a708-af44b820a2b9.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: tanyjnaaman/ped#7

**Comment by Graphcalibur** [comment]
Reason for not an issue: See #132
