### ISSUE TITLE
[PE-D] Application does not allow for partial search

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-W14-3/tp#131]
![image.png](https://raw.githubusercontent.com/soloplxya/ped/main/files/1e78e654-d0d5-4d44-bc32-3ca5b7ca25df.png)

![image.png](https://raw.githubusercontent.com/soloplxya/ped/main/files/dc0113cf-ff67-408d-9c55-fe34a318753a.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: soloplxya/ped#9

**Comment by Graphcalibur** [comment]
Reason for not an issue: This is the intentional design of the find command
