### ISSUE TITLE
[PE-D] Archived entries do not show and can confusion when users try to add an new entry that is already archived

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-W14-3/tp#138]
Here, company `ABCDE` is archived, and when users try to add a new `ABCDE` company, we get a generic message saying that the company already exists in the address book.

This can cause confusion since users may not realize that `ABCDE` is actually in the archive list, which is hidden

> ![image.png](https://raw.githubusercontent.com/cheehongw/ped/main/files/6df02941-667b-497d-a989-1fff86dd7290.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: cheehongw/ped#8

**Comment by Graphcalibur** [comment]
Can maybe change the message given? e.g. "In the list or archive" instead of "in the address book"
