### ISSUE TITLE
As a user, I can edit the details of a company

### ISSUE THREAD

**Issue by Graphcalibur** [AY2122S2-CS2103T-W14-3/tp#54]
so that I can keep the company details accurate and up to date

**Comment by Graphcalibur** [comment]
By the way, if the name of a company gets edited, I think we should also automatically edit the companyName attribute of any person/event whose companyName = name of the company that got edited.

**Comment by albertsutz** [comment]
Yes, just make sure to note this when describing it in the UG and DG
